export { upsertJsonProperty, upsertPackageDependency } from "./package-ops.js"
export type { JsonEditResult } from "./package-ops.js"
export { makeOverlayTree } from "./tree.js"
export type { OverlayTree, TreeChange, TreeChangeKind } from "./tree.js"
export { planIdentity, renderPlanSummary, unifiedFileDiff } from "./plan-identity.js"
export { applyOperations, compileHonoAdoptionPlan } from "./plan.js"
export type { CapabilityPlan, PlanOperation } from "./plan.js"
export { addNamedImport, registerHonoRoute } from "./typescript-ops.js"
export type { SourceEditResult } from "./typescript-ops.js"
