name: Bug
description: Something is wrong
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: What happened
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce
    validations:
      required: true
